version: 2.1

orbs:
    node: circleci/node@4

workflows:
    version: 2
    workflow:
        jobs:
            - build
            - lint:
                requires:
                    - build
            - test:
                requires:
                    - build
            - publish:
                requires:
                    - build
                    - lint
                    - test
                filters:
                    branches:
                        ignore: /.*/
                    tags: 
                        only: /^\d+\.\d+\.\d+(-.*)?/

executors:
    node:
        docker:
            - image: node:14

commands:
    attach_workspace_step:
        steps:
            - attach_workspace:
                at: ~/

jobs:
    build:
        executor: node
        steps:
            - checkout
            - node/install-packages
            - run:
                name: Build
                command: npx scri build
            - persist_to_workspace:
                root: ~/
                paths:
                    - project

    lint:
        executor: node
        steps:
            - attach_workspace_step
            - run:
                name: Lint
                command: npx scri lint

    test:
        executor: node
        environment:
            TS_NODE_PROJECT: test/tsconfig.json
        steps:
            - attach_workspace_step
            - run:
                name: Test
                command: npx nyc -- mocha --require ts-node/register --recursive test/**/*.spec.*

    publish:
        executor: node
        steps:
            - attach_workspace_step
            - run:
                name: Install dependencies
                command: |
                    curl -sL -o /usr/local/bin/jq https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64
                    chmod +x /usr/local/bin/jq
            - run:
                name: Set version
                command: |
                    jq ".version = \"<<pipeline.git.tag>>\"" package.json > package.json.temp
                    mv package.json.temp package.json
            - run:
                name: Package
                command: npx scri just-pack
            - run: 
                name: Publish package
                command: npm adduser \<<EOF
                    $NPM_USER
                    $NPM_TOKEN
                    $NPM_EMAIL
                    EOF
            - run: 
                name: Publish package
                command: npm publish scriptastic-<<pipeline.git.tag>>.tgz
