name: Pull Request

on:
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm
    
      - name: Install dependencies
        run: npm install

      - name: Build
        run: npx scri build

      - name: Persist workspace
        uses: actions/cache@v2
        with:
          key: workspace
          path: .
    
  lint:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Attach workspace
        uses: actions/cache@v2
        with:
          key: workspace
          path: .

      - name: Test
        run: npx scri lint

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Attach workspace
        uses: actions/cache@v2
        with:
          key: workspace
          path: .

      - name: Test
        run: npx scri test
